name: deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    # - name: Install
    #   uses: borales/actions-yarn@v2.0.0
    #   with:
    #     cmd: install
    # - name: Build
    #   uses: borales/actions-yarn@v2.0.0
    #   with:
    #     cmd: build
    - name: Deploy
      if: success()
      run: |
        cd public && sudo git init
        sudo git config user.name $GITHUB_ACTOR
        sudo git config user.email $GITHUB_ACTOR@users.noreply.github.com
        sudo git add .
        sudo git commit --allow-empty -m 'Deploy to GitHub pages'
        sudo git push --force --quiet https://$GITHUB_PAT@github.com/$GITHUB_REPOSITORY.git master:master
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
