name: deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install
      uses: ianwalter/puppeteer-container@v4.0.0
      with:
        args: yarn install
    - name: Build
      uses: ianwalter/puppeteer-container@v4.0.0
      with:
        args: yarn build
    - name: Deploy
      if: success()
      run: |
        cd dist && sudo git init
        sudo git config user.name $GITHUB_ACTOR
        sudo git config user.email $GITHUB_ACTOR@users.noreply.github.com
        sudo git add .
        sudo git commit --allow-empty -m 'Deploy to GitHub pages'
        sudo git push --force --quiet https://$GITHUB_PAT@github.com/$GITHUB_REPOSITORY.git master:master
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
